### ISSUE TITLE
Validate input json

### ISSUE THREAD

**Issue by kdabir** [kdabir/json-sql-console#4]
There are few validations that we can do on the json data for optimal user experience while running queries:

- [ ] It should be a parsable JSON array
- [ ] restrict number of items to 1000 (since its all sync, we don't want to freeze browser)
- [ ] have some upper cap on size in kb (need to figure out what size)?

**Comment by odininon** [comment]
This brings up a good point for #1. Do we want to show all 100 rows at once, or implement a paging solution?

Could even be a infinity scroll list, but sending them in chunks should help the render cycles.

**Comment by kdabir** [comment]
I was thinking about it for a while, as a perf optimization we can think about:
1. loading data in chunks in view
2. running sql engine in webworker instead of main loop.

If 1 is not too hard to do, we should go ahead with that, otherwise we are putting a soft limit of 1000 records anyways for now, that should help us get over the browser freeze pretty quickly. Some hacks with `setTimeout` can also take us some far before we have to "really" solve the proble.
